export const ENDPOINTS = {
    APPOINTMENT: "/appointment/",
    APPOINTMENTSTATUS: "/appointment-status/",
    APPOINTMENTTYPE: "/appointmenttype/",
    CLINICALSESSION: "/clinical-session/",
    CUSTOMERS: "/customers/",
    CURRENCY: "/currency/",
    DOCTOR: "/doctor/",
    EXCHANGERATE: "/exchangerate/",
    INVOICE: "/invoice/",
    PATIENT: "/patient/",
    PAYMENT: "/payment/",
    PAYMENTTERM: "/paymentterm/",
    RESOURCE: "/resource/",
    RESOURCETYPE: "/resource-type/",
    SESSIONPLAN: "/session-plan-treatment/",
    TREATMENT: "/treatment/",
    TREATMENTCATEGORY: "/treatment-category/",
    TREATMENTPLAN: "/treatment-plan-template/",
    USER: "/user/",
    ROLEPERMISSION: "/role-permission/",
    ROLE: "/role/",
    PERMISSION: "/permission/"
} as const;